### PR TITLE
Making alsamixer configurable, adding mouse support + minor fixes

### PR DESCRIPTION
**Pull request by braph**
Hello,

I'm using the alsamixer, but I am missing mouse support and the ability to configure it.
I implemented those things for myself now, maybe it would also be useful for others.

There are some commits that would even fit in the original alsamixer code without my rather heavy modifications, these are:

6eb0bc8f0848567f302e94ea5ee3a6d7c6966e65: _alsamixer: remove redundant sprintf() calls_
bef5b723a43f310ba73bcaa52f3da74ef5e08dde: _alsamixer: use mvwhline/mvwvline for drawing lines_
ae0604c93aa4bacbb678eb8ec832ad9e17c8b56a: _alsamixer: device_name.c: recognize DEL (ASCII 127) as backspace_
And maybe
485f3b0da1ffead2f88cffd9f2203516000415b5: _alsamixer: fix window_size_changed()_

Regards,

Benjamin

### CODE REVIEW

**Comment by takaswie** [comment]
Hi,

Thanks for the patchset. Although I'm interested in your idea to configure key bindings and add mouse support, the batch of patches includes refactoring, integrations, bug fixes and regression bandaids. As a reviewer, I think it better for you to respin your patchset into some smaller patchsets; i.e. bug fixes for current codebase, refactoring for the two new ideas, and integrations for them.
When posting the smaller patchsets, please ensure to add your sign-off.

Cheers.

**Comment by jkysela-rh** [comment]
+1

**Comment by perexg** [comment]
> I think it better for you to respin your patchset into some smaller patchsets

+1

**Comment by braph** [comment]
Hello again,

thanks for your fast anwser.
I have setup my fork from scratch and cleaned up the commits, the reference to the old repository therefore became invalid, so I think this PR can be closed.
Changes can be seen in https://github.com/braph/alsa-utils, the default config file is available at https://github.com/braph/alsamixer-misc/alsamixer.rc

Regards,

Benjamin

**Comment by perexg** [comment]
I would keep this open until new PR is created. Refer this PR from the new one. Thanks.

**Comment by perexg** [comment]
PR#28 is merged. If something is missing, let me know. Thank you.

**Pull request closed without merging**
