### PR TITLE
topology: pre-processor: Add support for enum controls

### PR DESCRIPTION
**Pull request by ranj063**
Add support for adding enum controls in the topology pre-processor.

### CODE REVIEW

**Review by singalsu — APPROVED** [review]
The enum control in SOF works with this update. Thanks a lot for adding this!

**Comment by singalsu** [comment]
@perexg Can this update get priority, the SOF topologies build fails without this.

**Review by lgirdwood — APPROVED** [review]
@perexg @tiwai fyi this is needed for enum kcontrols with topology2 and SOF v2.8

**Comment by singalsu** [comment]
Thanks @perexg !

**Pull request closed without merging**
