### PR TITLE
Added -T (timestamp) for --dump.

### PR DESCRIPTION
**Pull request by folkertvanheusden**
amidi could already trace/dump MIDI traffic (using --dump).
This patch adds a timestamp to that tracing.

### CODE REVIEW

**Comment by perexg** [comment]
Could you extend this patch to support also the monotonic timestamps ? `--timestamp realtime`  `--timestamp mono`  `--timestamp raw`

**Comment by folkertvanheusden** [comment]
@perexg done. Please see latest pull-request.

**Comment by perexg** [comment]
Thanks. You can change the code in the existing PR using 'git push -f' (force).

**Comment by folkertvanheusden** [comment]
What do you mean? Nothing happens with that?

See:

[image: image.png]

**Comment by perexg** [comment]
> What do you mean? Nothing happens with that? See: [image: image.png]

Push it to the identical branch which was used for the PR.

**Pull request closed without merging**
